version: '3'

services:
  qaslackbot:
    image: qaslackbot:qa
    hostname: qaslackbot
    env_file: QASlackBot.env

       # service deployment
    deploy:
      mode: replicated
      replicas: 1
      # service resource management
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      # service update configuration
      update_config:
        delay: 60s
        failure_action: continue
        monitor: 120s
        max_failure_ratio: 0.3
